apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-uaur
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-bundle-tenant/appstudio/dc-metro-map-uaur@sha256:7b87e02a335078829949170e67a0294cbf86190fe4700e51102485dae96eed4b
        name: my-nodejs
        resources: {}
status: {}
